apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: landcenter
  labels:
    app: {{ .Values.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      containers:
      - image: esphome/esphome:latest
        imagePullPolicy: Always
        name: {{ .Values.metadata.name }}
        ports:
        - containerPort: 6052
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: {{ .Values.metadata.name }}
          subPath: {{ .Values.metadata.name }}
        env:
          - name: ESPHOME_DASHBOARD_USE_PING
            value: "true"        
      restartPolicy: Always
      volumes:
      - name: {{ .Values.metadata.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.claim-Name }}