kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.metadata.name }}-tcp-service
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: {{ .Values.metadata.name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ip-nlb }}
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 6052